---
# tasks file for tomcat
- name: install tomcat9
  apt:
    name: tomcat9
    state: present

- name: copy .war files to Tomcat directory
  copy:
    src: /home/boxfuse/target/hello-1.0.war/158.160.2.1/home/boxfuse/target/hello-1.0.war
    dest: "{{ tomcat_dir }}"



