---
# tasks file for tomcat
- name: install tomcat9
  apt:
    name: tomcat9
    state: present

- name: copy .war files
  copy:
    src: /158.160.30.66/home/boxfuse/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps



