---
# tasks file for provisioning
- name: install package for maven
  apt: name="{{item}}" state=present
  with_items:
   - maven
   - git
   - default-jdk

- name: clone boxfuse from git
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: "{{ dest_folder }}"
    clone: yes

- name: run mvn package
  shell: mvn package
  args:
    chdir: "{{ dest_folder }}"

- name: synchronize .war files between local and remote server
  synchronize:
    mode: pull
    src: rsync://130.193.53.159/home/boxfuse/target/hello-1.0.war
    dest: home/boxfuse/target/hello-1.0.war

