---
# tasks file for provisioning
- name: install package for maven
  apt: name={{item}} state=present update_cache: yes
  with_items:
   - maven
   - git
   - default-jdk

- name: clone boxfuse from git
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: {{ dest_folder }}
    clone: yes

- name: run mvn package
  shell: mvn package
  args:
    chdir: {{ dest_boxfuse }}

- name: fetch .war files
  synchronize:
    src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dest: /home/boxfuse
    mode: pull
