---
# tasks file for provisioning
- name: install package for maven
  apt: name={{ item }} state=present
  with_items:
    - maven
    - git
    - default-jdk
    update_cache: yes

- name: clone boxfuse from git
- git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: /srv/checkout
    clone: yes