---
# tasks file for provisioning
- name: install package for maven
  apt: name="{{item}}" state=present
  with_items:
   - maven
   - git
   - default-jdk

- name: clone boxfuse from git
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: "{{ dest_folder }}"
    clone: yes

- name: run mvn package
  shell: mvn package
  args:
    chdir: "{{ dest_boxfuse }}"

- name: fetch .war files
  fetch:
    src: /home/boxfuse/target/hello-1.0.war
    dest: /home/boxfuse

